Add Volume Output to Video Layer Node
StitchDesign/Stitch pull request #315
Opened 2024-09-19 23:08 UTC by narner

https://github.com/user-attachments/assets/53b99641-9c32-4f8f-9878-1983cd06d658

2024-09-19 23:10 UTC, ellbosch commented on Stitch/Graph/Node/Layer/Type/VisualMediaLayerNode.swift
> +            volume: viewModel.volume.getNumber ?? 0.5
Does this match Origami's default volume?

2024-09-19 23:11 UTC, ellbosch commented on Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Video/StitchVideoPlayer.swift
> +var DEFAULT_VIDEO_PLAYER_VOLUME = 0.5
Please move this inside StitchVideoImportPlayer and make it both static and _constant_ please!

2024-09-19 23:11 UTC, narner commented on Stitch/Graph/Node/Layer/Type/VisualMediaLayerNode.swift
> +            volume: viewModel.volume.getNumber ?? 0.5
Ah no; there's is 1; good catch

2024-09-19 23:14 UTC, ellbosch commented on Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Video/StitchVideoPlayer.swift
> +        self.muteSound() // Mute initially or customize if needed.
This looks redundant.

2024-09-19 23:15 UTC, ellbosch commented on Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Video/StitchVideoPlayer.swift
> +        self.video.volume = Float(volume)
```suggestion
        let volume = min(1, max(0, volume))
        self.video.volume = Float(volume)
```

2024-09-19 23:16 UTC, ellbosch commented on Stitch/Graph/Node/Port/View/Field/InputView/ScrubbedVideoView.swift
> +        videoPlayer.setVolume(volume: volume)
```suggestion
        // Set volume when the view is created
        videoPlayer.setVolume(volume: volume)
```
```suggestion
        self.videoPlayer.setVolume(volume: volume)
        // Set volume when the view is created
        videoPlayer.setVolume(volume: volume)
```

2024-09-19 23:17 UTC, ellbosch requested changes
Good start. Please test this with video scrubbing to make sure we get expected behavior there.

2024-09-20 00:38 UTC, ellbosch approved these changes

2024-09-20 00:39 UTC, merged